pub_rate = 10000

[[publications]]
clients = 5
topic_name = "/topic/01"

[[publications]]
clients = 5
topic_name = "/topic/02"

[[subscription]]
clients = 5
topic_filter = "/topic/01/+"

[[subscription]]
clients = 5
topic_filter = "/topic/02/+"
